# Generated by Django 5.0.3 on 2024-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_sucursal', models.CharField(max_length=20)),
                ('tamaño', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=20)),
                ('cantidad_de_empleados', models.CharField(max_length=20)),
            ],
        ),
    ]
